apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.defaults.labels }}
spec:
  provider: {{ .Values.spc.provider }}
  parameters:
    region: {{ .Values.spc.region }}
    objects: |  
      - objectName: {{ .Values.defaults.labels }}-preprod
        objectType: secretsmanager
        jmesPath:
          - path: MONGO_INITDB_DATABASE
            objectAlias: MONGO_INITDB_DATABASE
  secretObjects:
    - secretName: {{ .Values.defaults.labels }}-preprod
      type: Opaque
      data:
        - objectName: MONGO_INITDB_DATABASE
          key: MONGO_INITDB_DATABASE
