apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.defaults.labels }}
spec:
  provider: {{ .Values.spc.provider }}
  parameters:
    region: {{ .Values.spc.region }}
    objects: |  
      - objectName: {{ .Values.defaults.labels }}-preprod
        objectType: secretsmanager
        jmesPath:
          - path: INSTANA_AUTO_PROFILE
            objectAlias: INSTANA_AUTO_PROFILE
          - path: MONGO_URL
            objectAlias: MONGO_URL
          - path: GO_SLOW
            objectAlias: GO_SLOW
          - path: CATALOGUE_SERVER_PORT
            objectAlias: CATALOGUE_SERVER_PORT
  secretObjects:
    - secretName: {{ .Values.defaults.labels }}-preprod
      type: Opaque
      data:
        - objectName: INSTANA_AUTO_PROFILE
          key: INSTANA_AUTO_PROFILE
        - objectName: MONGO_URL
          key: MONGO_URL
        - objectName: GO_SLOW
          key: GO_SLOW
        - objectName: CATALOGUE_SERVER_PORT
          key: CATALOGUE_SERVER_PORT
