apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cart.fullname" . }}
  labels:
    {{- include "cart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deploy.replicaCount }}
  selector:
    matchLabels:
      {{- include "cart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "cart.annotations" . | nindent 8 }}
    spec:
      {{- with .Values.deploy.tolerations }}
      tolerations:
        - key: {{ .key }}
          operator: {{ .operator }}
          value: {{ .value }}
      {{- end }}
      {{- with .Values.deploy.affinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .nodeAffinity.key }}
                operator: {{ .nodeAffinity.operator }}
                values:
                - {{ .nodeAffinity.values }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deploy.image.repository }}:{{ .Values.deploy.image.tag }}"
          imagePullPolicy: {{ .Values.deploy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.deploy.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deploy.readinessProbe.path }}
              port: http
              scheme: {{ .Values.deploy.readinessProbe.scheme }}
            initialDelaySeconds: {{ .Values.deploy.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deploy.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.deploy.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.deploy.readinessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.deploy.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deploy.livenessProbe.path }}
              port: http
              scheme: {{ .Values.deploy.livenessProbe.scheme }}
            initialDelaySeconds: {{ .Values.deploy.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deploy.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.deploy.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.deploy.livenessProbe.successThreshold }}
          {{- end }}
          env:
            {{- range .Values.deploy.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.deploy.resources | nindent 12 }}
      restartPolicy: {{ .Values.deploy.restartPolicy }}
