version: 0.2
env:
  parameter-store:
    AWS_ACCOUNT_ID: /CodeBuild/Docker/AWS_ACCOUNT_ID
    CODECOMMIT_USER: /CodeBuild/CODECOMMIT/USER
    CODECOMMIT_PASS: /CodeBuild/CODECOMMIT/PASS
    SLACK_WEBHOOK_URL: /CodeBuild/SLACK/WEBHOOK_URL
phases:
    pre_build:
        commands:
            - echo "LOGIN TO ECR....................."
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT
    build:
        commands:
            - echo "UPDATING SHFILES PERMISSION....................."
            - chmod +x slack/build_notify.sh && chmod +x slack/deploy_notify.sh

            - echo "UPDATING DOCKER IMAGE VERSION....................."
            - LATEST_TAG=$(aws ecr describe-images --repository-name $PROJECT --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text || echo "v1.0.0")
            - PRE_VERSION=$(aws ecr describe-images --repository-name $PROJECT --query 'sort_by(imageDetails,& imagePushedAt)[-2].imageTags[0]' --output text || echo "v1.0.0")
            - |
                if [ "$LATEST_TAG" = "None" ]; then LATEST_TAG="v1.0.0"; fi
                IFS='.' read MAJOR MINOR PATCH <<EOF
                $(echo "$LATEST_TAG")
                EOF
                export TAG="$MAJOR.$MINOR.$((PATCH+1))"
                export OLD_TAG="$MAJOR.$MINOR.$PATCH"

            - echo "SENDING SLACK NOTIFICATION..................."
            - ./slack/build_notify.sh

            - echo "BUILDING DOCKER IMAGE................."
            - docker buildx create --name shopstack
            - docker buildx use shopstack
            - docker buildx build --push . -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT:$TAG --cache-from type=registry,ref=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT:$OLD_TAG --cache-to type=inline
            
            - echo "CLONING REPO AND UPDATING GIT USER................"
            - |
                git clone https://github.com/Uj5Ghare/Kops-Microservices-Project.git -b $CODECOMMIT_BRANCH
                cd Kops-Microservices-Project
                git checkout $CODECOMMIT_BRANCH
                git config --global user.email ujwal5ghare@gmail.com
                git config --global user.name Uj5Ghare

            - echo "UPDATING DOCKER IMAGE TAG AND PUSH TO REPO..............."
            - |
                sed -i "s/tag: .*/tag: $TAG/" $FILE_PATH
                git add .
                git commit -m "[CI/CD](Updated) docker image tag to $TAG with CI/CD in $PROJECT"
                git push origin $CODECOMMIT_BRANCH
                
            - echo "SENDING SLACK NOTIFICATION..................."
            - ./slack/deploy_notify.sh