defaults:
  namespace:
    name: shopstack
    enabled: false
  labels: catalogue
  managedBy: Helm
  annotations:
    lang: nodejs

# DEPLOYMENT CONFIGURATION
deploy:
  replicaCount: 1
  image:
    repository: ghcr.io/shopstack/shopstack-catalogue
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      key: app
      operator: In
      values: shopstack
  strategy:
    type: RollingUpdate
    maxSurge: 50%
    maxUnavailable: 0
  resources:
    requests:
      memory: "200Mi" 
      cpu: "100m"
    limits:
      memory: "500Mi"
      cpu: "200m"
  restartPolicy: Always
  readinessProbe:
    enabled: true
    path: /
    scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    enabled: true
    path: /
    scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  tolerations:
    key: app
    operator: Equal
    value: shopstack
  env:
    - name: MONGO_URL
      value: "mongodb://mongodb:27017/catalogue"
    - name: GO_SLOW
      value: "0"
    - name: CATALOGUE_SERVER_PORT
      value: "8080"
    - name: INSTANA_AUTO_PROFILE
      value: "true"

# SERVICE CONFIGURATION
service:
  type: ClusterIP
  ports:
    http:
      name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

# INGRESS CONFIGURATION
ingress:
  enabled: false
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: catalogue.shopstack.local
  path: /
  pathType: Prefix

# HORIZONTAL POD AUTOSCALER CONFIGURATION
hpa:
  enabled: true
  maxReplicas: 3
  minReplicas: 1
  cpu:
    metrics:
      resourceName: cpu
      averageUtilization: 70
      type: Utilization
  behavior:
    scaleDown:
      policies:
        periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Min
      stabilizationWindowSeconds: 180
    scaleUp:
      policies:
        periodSeconds: 15
        type: Percent
        value: 30
      selectPolicy: Min
      stabilizationWindowSeconds: 500

# SECRET CONFIGURATION
secret:
  enabled: false
  name: catalogue-secret
  type: Opaque
  data: ""

# POD DISRUPTION BUDGET CONFIGURATION
pdb:
  enabled: true
  minAvailable: 1

# SECRET PROVIDER CLASS CONFIGURATION
spc:
  provider: aws
  region: ap-south-1
  objects:
    INSTANA_AUTO_PROFILE: INSTANA_AUTO_PROFILE
    MONGO_URL: MONGO_URL
    GO_SLOW: GO_SLOW
    CATALOGUE_SERVER_PORT: CATALOGUE_SERVER_PORT

configMap:
  enabled: false
