apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.defaults.labels }}
spec:
  provider: {{ .Values.spc.provider }}
  parameters:
    region: {{ .Values.spc.region }}
    objects: |  
      - objectName: {{ .Values.defaults.labels }}-preprod
        objectType: secretsmanager
        jmesPath:
          - path: AMQP_HOST
            objectAlias: AMQP_HOST
          - path: DISPATCH_ERROR_PERCENT
            objectAlias: DISPATCH_ERROR_PERCENT
  secretObjects:
    - secretName: {{ .Values.defaults.labels }}-preprod
      type: Opaque
      data:
        - objectName: AMQP_HOST
          key: AMQP_HOST
        - objectName: DISPATCH_ERROR_PERCENT
          key: DISPATCH_ERROR_PERCENT
