apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.defaults.labels }}
spec:
  provider: {{ .Values.spc.provider }}
  parameters:
    region: {{ .Values.spc.region }}
    objects: |  
      - objectName: {{ .Values.defaults.labels }}-preprod
        objectType: secretsmanager
        jmesPath:
          - path: CATALOGUE_HOST
            objectAlias: CATALOGUE_HOST
          - path: USER_HOST
            objectAlias: USER_HOST
          - path: CART_HOST
            objectAlias: CART_HOST
          - path: SHIPPING_HOST
            objectAlias: SHIPPING_HOST
          - path: PAYMENT_HOST
            objectAlias: PAYMENT_HOST
          - path: RATINGS_HOST
            objectAlias: RATINGS_HOST
          - path: INSTANA_AGENT_KEY
            objectAlias: INSTANA_AGENT_KEY
          - path: INSTANA_EUM_KEY
            objectAlias: INSTANA_EUM_KEY
          - path: INSTANA_EUM_REPORTING_URL
            objectAlias: INSTANA_EUM_REPORTING_URL
  secretObjects:
    - secretName: {{ .Values.defaults.labels }}-preprod
      type: Opaque
      data:
        - objectName: CATALOGUE_HOST
          key: CATALOGUE_HOST
        - objectName: USER_HOST
          key: USER_HOST
        - objectName: CART_HOST
          key: CART_HOST
        - objectName: SHIPPING_HOST
          key: SHIPPING_HOST
        - objectName: PAYMENT_HOST
          key: PAYMENT_HOST
        - objectName: RATINGS_HOST
          key: RATINGS_HOST
        - objectName: INSTANA_AGENT_KEY
          key: INSTANA_AGENT_KEY
        - objectName: INSTANA_EUM_KEY
          key: INSTANA_EUM_KEY
        - objectName: INSTANA_EUM_REPORTING_URL
          key: INSTANA_EUM_REPORTING_URL
