apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.defaults.labels }}
spec:
  provider: {{ .Values.spc.provider }}
  parameters:
    region: {{ .Values.spc.region }}
    objects: |  
      - objectName: {{ .Values.defaults.labels }}-preprod
        objectType: secretsmanager
        jmesPath:
          - path: CART_ENDPOINT
            objectAlias: CART_ENDPOINT
          - path: DB_HOST
            objectAlias: DB_HOST
  secretObjects:
    - secretName: {{ .Values.defaults.labels }}-preprod
      type: Opaque
      data:
        - objectName: CART_ENDPOINT
          key: CART_ENDPOINT
        - objectName: DB_HOST
          key: DB_HOST
